name: "COD Oil Price Scraper"
description: "Scrapes heating oil prices from COD Oil and updates Home Assistant"
version: "1.5.3"
slug: "cod_oil_scraper"
init: false
url: https://github.com/Former-Stranger/cod_oil_scraper
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
options:
  zipcode: ""
  ha_token: ""
  schedule_hour: 0
  schedule_minute: 0
  log_level: "info"
schema:
  zipcode: str
  ha_token: str
  schedule_hour: int(0,23)
  schedule_minute: int(0,59)
  log_level: list(debug|info|warning|error)
