name: "COD Oil Price Scraper"
description: "Scrapes heating oil prices from COD Oil and updates Home Assistant"
version: "1.0.5"
slug: "cod_oil_scraper"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
hassio_api: true
hassio_role: homeassistant
auth_api: true
homeassistant_api: true
ingress: false
options:
  zipcode: "06810"
  schedule_hour_1: 9
  schedule_hour_2: 15
  log_level: "info"
schema:
  zipcode: str
  schedule_hour_1: int(0,23)
  schedule_hour_2: int(0,23)
  log_level: list(debug|info|warning|error)
