name: "COD Oil Price Scraper"
description: "Scrapes heating oil prices from COD Oil and updates Home Assistant"
version: "1.4.1"
slug: "cod_oil_scraper"
init: false
url: https://github.com/Former-Stranger/cod_oil_scraper
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
homeassistant_api: true
options:
  zipcode: "06810"
  schedule_hour_1: 9
  schedule_hour_2: 15
  log_level: "info"
schema:
  zipcode: str
  schedule_hour_1: int(0,23)
  schedule_hour_2: int(0,23)
  log_level: list(debug|info|warning|error)
